name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        id: playwright
        continue-on-error: true
        run: npx playwright test

      - name: Upload Playwright Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Send Email Notification
        if: ${{ !cancelled() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}

          from: ${{ secrets.SMTP_USERNAME }}

          to: |
            ${{ secrets.EMAIL_TO_1 }}
            ${{ secrets.EMAIL_TO_2 }}

          subject: "Playwright Test Result - ${{ steps.playwright.outcome }}"

          body: |
            Hello,

            Playwright automation test execution has completed.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Test Status: ${{ steps.playwright.outcome }}

            Test result:
            - PASS = Tests passed
            - FAIL = One or more tests failed

            Please check GitHub Actions for the detailed Playwright report.

            Regards,
            QA Automation

      - name: Mark workflow as failed
        if: ${{ steps.playwright.outcome == 'failure' }}
        run: exit 1